In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Matrix Notation and matrix multiplication

$$2u + v + w = 5\\
4u - 6v    = -2\\
-2u + 7v + 2w = 9$$

- matrix form

$$ Ax = b$$
$$ x = 
\begin{bmatrix}
u\\
v\\
w
\end{bmatrix}$$

$$ b =
\begin{bmatrix}
5\\
-2\\
9
\end{bmatrix}$$

$$ A = 
\begin{bmatrix}
2&1&1\\
4&-6&0\\
-2&7&2
\end{bmatrix}$$


In [21]:
# Defining all in numpy
A = np.array([[2, 1, 1], 
             [4, -6, 0], 
             [-2, 7, 2]])
x = np.array(['u', 'v', 'w'])
b = np.array([5, -2, 9])

In [22]:
# Solve linear equation in numpy
np.linalg.solve(A, b)

array([1., 1., 2.])

### Matrix multiplication
$$\begin{bmatrix}
1&1&6\\
3&0&1\\
1&1&4
\end{bmatrix}
\begin{bmatrix}
2\\
5\\
0
\end{bmatrix}
=
\begin{bmatrix}
1.2+1.5+6.0\\
3.2+0.5+3.0\\
1.2+1.5+4.0
\end{bmatrix}
=
\begin{bmatrix}
7\\
6\\
7
\end{bmatrix}
$$

In [7]:
# Matrix multiplication
m1 = np.array([[1, 1, 6],
              [3, 0, 1]
              ,[1, 1, 4]])
m2 = np.array([2, 5, 0])
m1 @ m2.T

array([7, 6, 7])

### Inner product
$$\begin{bmatrix}
2&1&1
\end{bmatrix}
\begin{bmatrix}
1\\
1\\
2
\end{bmatrix}
=
\begin{bmatrix}
2.1 + 1.1 + 1.2
\end{bmatrix}
= [5]$$

In [8]:
#Inner product
m1 = np.array([2, 1, 1])
m2 = np.array([1, 1, 2])
m1 @ m2.T

5

### Inverse of matrix
$$AA^{-1}=I\\A^{-1}A=I$$


In [17]:
#inverse of matrix
A = np.array([[2, 1, 1],
             [4, -6, 0],
             [-2, 7, 2]])
A_inverse = np.linalg.inv(A)
A_inverse

array([[ 0.75  , -0.3125, -0.375 ],
       [ 0.5   , -0.375 , -0.25  ],
       [-1.    ,  1.    ,  1.    ]])

### Transpose of matrix

$$A=\begin{bmatrix}
2&1&4\\
0&0&3
\end{bmatrix}$$

$$A^{T} = \begin{bmatrix}
2&0\\
1&0\\
4&3
\end{bmatrix}
$$

$(A^{-1})^TA^T = I$

In [18]:
A = np.array([[2, 1, 4], [0, 0, 3]])
A.T

array([[2, 0],
       [1, 0],
       [4, 3]])

In [23]:
#Determinant of matrix
#np.linalg.det(A)