
Matrix-Vector Products:

The matrix below gives the probabilities of moving from 1 health state to another in 1 year. If the current health states for a group are:

    85% asymptomatic
    10% symptomatic
    5% AIDS
    0% death

what will be the % in each health state in 1 year?


In [1]:
import numpy as np

In [2]:
# Repersenting Matrix in numpy
m1 = np.array([0.85, .1, .05, 0])
m1

array([0.85, 0.1 , 0.05, 0.  ])

In [3]:
m2 = np.array([[0.9, 0.07, 0.02, 0.01], [0, 0.93, 0.05, 0.02], [0, 0, 0.85, 0.15], [0, 0, 0, 1.00]])
m2

array([[0.9 , 0.07, 0.02, 0.01],
       [0.  , 0.93, 0.05, 0.02],
       [0.  , 0.  , 0.85, 0.15],
       [0.  , 0.  , 0.  , 1.  ]])

In [6]:
# Doing transpose and muliplying
# in python 3 @ repersents multiplication
m2.T @ m1.T

array([0.765 , 0.1525, 0.0645, 0.018 ])